server:
  port: 8084

spring:
  application:
    name: transfers-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/transfers_db}
    username: ${DB_USERNAME:fintech}
    password: ${DB_PASSWORD:fintech}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

services:
  accounts-service:
    base-url: ${ACCOUNTS_SERVICE_URL:http://localhost:8082}
  ledger-service:
    base-url: ${LEDGER_SERVICE_URL:http://localhost:8083}

management:
  endpoints:
    web:
      exposure:
        include: health,info
