# Managed by Kustomize.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-banking
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: web-banking
          image: ghcr.io/fintech-platform/web-banking:dev-latest
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
