# Managed by Kustomize.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-banking
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: web-banking
          image: ghcr.io/fintech-platform/web-banking:REPLACE_AT_DEPLOY
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 128Mi
