# Managed by Kustomize.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfers-service
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: transfers-service
          image: ghcr.io/fintech-platform/transfers-service:uat-latest
          resources:
            requests:
              cpu: 150m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 768Mi
